baseURL = "http://cfcfd.mechmining.uq.edu.au/eilmer/"
languageCode = "en-us"
title = "Eilmer"
theme = "hyde"
canonifyURLs = true

[params]
  description = "An open source compressible flow simulation tool, built in the D programming language."
  author = "Peter A. Jacobs and Rowan J. Gollan"

[menu]

   [[menu.main]]
      name = "Reference Guide"
      url = "/html/reference-guide.html"
      weight = 25
